### ISSUE TITLE
using standalone tool on ICGC data.

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio.variation#32]
Hi Brad;

I would like to know if I can use this standalone software on VCF called algorithms other than (vardict, freebayes, mutect, varscan) ? My VCF belong to the same version 4.0. 

My aim is to find consensus regions of vcf obtained from ICGC. In ICGC there are 3 vcf type which belong to 3 centers. Right now I have vcfs from Sanger and DKFZ/EMBL called by different algorithms such as caveman, platypus, pindel, delly. ( for different purposes of course (indel or snv)). 

Will this software work on my case?

Best regards,

Tunc.

**Comment by chapmanb** [comment]
Tunc;
In general the tools should work on other VCF callers. I'd suggest using the new simpler ensemble caller rather than this version:

https://github.com/chapmanb/bcbio.variation.recall#ensemble

If there are VCF validation issues or other problems you may have to handle those prior to feeding into the tools. Hope this helps.
